In [1]:
import numpy as np

In [54]:
lst = [9, 6, 7, 2, 3, 1]

In [55]:
a = np.array(lst)
a

array([9, 6, 7, 2, 3, 1])

In [56]:
b = np.zeros((4, 4))
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [57]:
upper_ind = np.triu_indices(4, 1)
upper_ind

(array([0, 0, 0, 1, 1, 2]), array([1, 2, 3, 2, 3, 3]))

In [58]:
b[upper_ind] = a

In [59]:
b

array([[ 0.,  9.,  6.,  7.],
       [ 0.,  0.,  2.,  3.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [60]:
b + b.T

array([[ 0.,  9.,  6.,  7.],
       [ 9.,  0.,  2.,  3.],
       [ 6.,  2.,  0.,  1.],
       [ 7.,  3.,  1.,  0.]])